version: 1.2
workflows:
  - name: SnTestingWdl
    subclass: WDL
    primaryDescriptorPath: /sn_testing.wdl
    readMePath: /testing.README.md
    testParameterFiles:
      - /sn_testing.wdl

  - name: SnTestingWdl2
    subclass: WDL
    primaryDescriptorPath: /sn_testing_2.wdl
    readMePath: /testing.README.md
    testParameterFiles:
      - /sn_testing_2.wdl

  - name: NsTestingWdl
    subclass: WDL
    primaryDescriptorPath: /ns_testing.wdl
    readMePath: /testing.README.md
    testParameterFiles:
      - /ns_testing.wdl