version: 1.2
workflows:
  - name: SnTestingWdl
    subclass: WDL
    primaryDescriptorPath: /sn_testing.wdl
    readMePath: /testing.README.md
    testParameterFiles:
      - /sn_testing.wdl

  - name: Mad4Hatter
    subclass: WDL
    primaryDescriptorPath: /Mad4Hatter.wdl
    readMePath: /Mad4Hatter.README.md
    testParameterFiles:
      - /Mad4Hatter.wdl

  - name: NsTestingWdl
    subclass: WDL
    primaryDescriptorPath: /ns_testing.wdl
    readMePath: /testing.README.md
    testParameterFiles:
      - /ns_testing.wdl