version: 1.2
workflows:
  - name: SnTestingWdl
    subclass: WDL
    primaryDescriptorPath: /sn_testing.wdl
    readMePath: /testing.README.md
    testParameterFiles:
      - /sn_testing.wdl

  - name: SnTestingWdlWithCpuPlatform
    subclass: WDL
    primaryDescriptorPath: /sn_testing_cpu_platform.wdl
    readMePath: /testing.README.md
    testParameterFiles:
      - /sn_testing_cpu_platform.wdl

  - name: Mad4Hatter
    subclass: WDL
    primaryDescriptorPath: /Mad4Hatter.wdl
    readMePath: /Mad4Hatter.README.md
    testParameterFiles:
      - /Mad4Hatter.wdl

  - name: Mad4HatterQcOnly
    subclass: WDL
    primaryDescriptorPath: /Mad4HatterQcOnly.wdl
    readMePath: /Mad4HatterQcOnly.README.md
    testParameterFiles:
      - /Mad4HatterQcOnly.wdl

  - name: Mad4HatterPostProcessing
    subclass: WDL
    primaryDescriptorPath: /Mad4HatterPostProcessing.wdl
    readMePath: /Mad4HatterPostProcessing.README.md
    testParameterFiles:
      - /Mad4HatterPostProcessing.wdl

  - name: NsTestingWdl
    subclass: WDL
    primaryDescriptorPath: /ns_testing.wdl
    readMePath: /testing.README.md
    testParameterFiles:
      - /ns_testing.wdl

  - name: GetZipFiles
    subclass: WDL
    primaryDescriptorPath: /get_zip_files.wdl
    readMePath: /testing.README.md
    testParameterFiles:
      - /get_zip_files.wdl
