version: 1.2
workflows:
  - name: SnTestingWdl
    subclass: WDL
    primaryDescriptorPath: /sn_testing.wdl
    readMePath: /testing.README.md
    testParameterFiles:
      - /sn_testing.wdl

  - name: main
    subclass: WDL
    primaryDescriptorPath: /main.wdl
    readMePath: /main.README.md
    testParameterFiles:
      - /main.wdl

  - name: NsTestingWdl
    subclass: WDL
    primaryDescriptorPath: /ns_testing.wdl
    readMePath: /testing.README.md
    testParameterFiles:
      - /ns_testing.wdl